{% set name = "libpulsar" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/pulsar-client-cpp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4b8016303f55bd0c02f9b0c11c637b0916d91dba4a68498ced8d74de5b95dc42

build:
  number: 0
  skip: true  # [win]
  # pulsar doesn't give any ABI guarantees
  run_exports:
    - {{ pin_subpackage('libpulsar', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - sed
  host:
    - boost-cpp
    - gmock
    - gtest
    - libcurl
    - libprotobuf
    - openssl
    - snappy
    - zlib
    - zstd

test:
  commands:
    - test -f $PREFIX/lib/libpulsar${SHLIB_EXT}


about:
  home: https://github.com/apache/pulsar-client-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Apache Pulsar C++ client library

extra:
  recipe-maintainers:
    - xhochy
